#55 - class attributes separation and useless parenthesis fixers
blumilksoftware/codestyle pull request #56
Opened 2022-04-07 11:07 UTC by kamilpiech97

This should close #55.
Added `NoUselessParenthesisFixer` and `ClassAttributesSeparationFixer` from Kuba Werłos custom fixers.

**ClassAttributesSeparationFixer**
Before:
```
<?php

class classAttributesSeparationExample
{
    protected string $exampleA;
    protected string $exampleB;

    public function testFunctionA(string $a): string
    {
        return $a;
    }
    public function testFunctionB(string $b): string
    {
        return $b;
    }
}
```

After:
```
<?php

declare(strict_types=1);

class classAttributesSeparationExample
{
    protected string $exampleA;

    protected string $exampleB;

    public function testFunctionA(string $a): string
    {
        return $a;
    }

    public function testFunctionB(string $b): string
    {
        return $b;
    }
}
```

**NoUselessParenthesisFixer**
Before:
```
<?php

declare(strict_types=1);

if (($a === 1))
{

}
```

After:
```
<?php

declare(strict_types=1);

if ($a === 1)
{
}
```

2022-04-07 11:37 UTC, krzysztofrewak requested changes

2022-04-07 11:37 UTC, krzysztofrewak commented on src/Config.php
> +
Hm, I would prefer to have properties without empty lines between them. Probably you need to set `'property' => 'one'` in your fixer.

2022-04-07 20:18 UTC, krzysztofrewak approved these changes

2022-04-08 06:50 UTC, Baakoma approved these changes

2022-04-08 07:03 UTC, merged